### ISSUE TITLE
Profile Issue

### ISSUE THREAD

**Issue by dennyfranklin** [fssa-batch3/prasanna.mohanram__web_project#3]
### Description of issue
I don't know how to go to the profile page.

### Expected result
I want to go to my profile page.

### Actual result
After logged in it redirect to profile page ,but if i want to specifically edit my profile ,I don't know how to go.

### Steps to reproduce
1. Signed up to the webpage
2. Redirected to home page, after logged in.  
3.Unable to get the user session back

```
Path:      /
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-IN
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--bikerzzone.netlify.app%2F&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--bikerzzone.netlify.app/)

**Comment by BrokenPRasanna** [comment]
Issue solved👍

**Comment by dennyfranklin** [comment]
He solved the issue
